### ISSUE TITLE
Skill movements

### ISSUE THREAD

**Issue by Aryan14** [romdi/IOS-Assets#13]
Any place to create some skill movements in IOS ?
Of course many of those skill movements are hard to implement in IOS  (Ronaldo chop, Elastico, AKKA, Cruyff turn etc) but some 'easy' ones should be possible.
- Back heel (passes)
- Lifting ball up (ball juggle)
- Precision dribbling
- Fake shots
- Ball flick
- Stepover right/left
- Roulette
- Simple rainbow
- Turn spin left/right
- Double touch
- Rabona
- Scoop turn (https://www.youtube.com/watch?v=cD8et-dYryQ)
- No-look pass (with +reload maybe?)

Currently the 'Overhead flick' is the only 'skill movement' in IOS.

**Comment by romdi** [comment]
Back heel and lifting the ball up could work to some extend, like overhead flick works now. Can you elaborate on the precision dribbling?

**Comment by Aryan14** [comment]
http://www.youtube.com/watch?v=xVY_c7J8ni8

**Comment by ghost** [comment]
I think backheel is something that we should definitely see if we can get in. The others are bit different I think. Precision dribbling in particular, I'm not sure it'd fit in with the style of the game as it is. Fake shots could be worth implementing, it's just an animation I guess. Not sure about lifting the ball up, what would you use it for?

**Comment by Aryan14** [comment]
Added some

**Comment by Aryan14** [comment]
Going to be against this idea. Read: https://github.com/romdi/IOS/issues/231

**Comment by Aryan14** [comment]
Already got this implemented so can be closed.
