### ISSUE TITLE
Change game name

### ISSUE THREAD

**Issue by Aryan14** [romdi/IOS-Assets#17]
Maybe we should say goodbye to ´International Online Soccer´.
- Shortname is IOS and is the same brand the iOS.
- Players and 'old' new players will still think of the old IOS. (bad memories etc)

Although question is, what would be the new name?
- Global Online Soccer
- Global Soccer Online
- World(wide) Online Soccer
- World(wide) Soccer Online
- International Soccer Online
- International Online Football
- International Football Online
- Online Soccer
- Soccer Online
- Let's Play Football!
- Revolution Online Soccer
- International Online Soccer Deluxe
- International Online Soccer Revolution
- International Online Soccer 2 
- International Online Soccer Reborn
- International Online Soccer Evolution
- International Online Soccer We're back!

In all honestly I would keep IOS but yea... Maybe like IOS:R (revolution) IOS:D (deluxe) ? to still keep 'IOS'

**Comment by ghost** [comment]
If we changed the name it would need to not contain the IOS acronym. It's something we do need to think carefully about. I couldn't really say which is the best option at the moment.

**Comment by Aryan14** [comment]
It's better to close this.
