### ISSUE TITLE
Offside bug - The ball isn't the offside line in IOS

### ISSUE THREAD

**Issue by Fonzik** [romdi/IOS-Assets#21]
In IOS, the ball is not the offside line. In IOS the offside line is the defenders.

![300px-OffsideBallLine svg](https://f.cloud.github.com/assets/3081269/75811/1f0e51ec-60d7-11e2-9264-dca3ae532bf5.png)

**Comment by Aryan14** [comment]
Are you sure? I think the ball is the offside line if you are past the defenders.
